version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASS
      TZ: Asia/Tokyo
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql-data:/var/lib/mysql
    platform: linux/x86_64
  web:
    build: .
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
    stdin_open: true
    tty: true

volumes:
  mysql-data:
    driver: local

networks:
  default:
    name: fcj-management
