version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: $DB_PASS
      MYSQL_DATABASE: $DB_NAME
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    platform: linux/x86_64
  web:
    build: .
    environment:
      TZ: Asia/Tokyo
      DB_HOST: $DB_HOST
      DB_NAME: $DB_NAME
      DB_USER: $DB_USER
      DB_PASS: $DB_PASS
    ports:
      - "5000:5000"
    depends_on:
      - db
    stdin_open: true
    tty: true

volumes:
  mysql-data:
    driver: local

networks:
  default:
    name: fcj-management
